### ISSUE TITLE
Add extrinsic to update a user's escrow stake

### ISSUE THREAD

**Issue by sander2** [interlay/interbtc#1007]
- add an extrinsic that updates a user's stake
- extrinsic should be callable by everyone (also for other users)
- Possibly make this extrinsic free of charge if it changes the stake by more than e.g. 1%
- In theory this incentivizes users to report everyone else, s.t. their stake remains higher in comparison (but in reality this is unlikely to happen without UI support).
- We can have either an off-chain worker, or an interlay bot call this extrinsic periodically

**Comment by gregdhill** [comment]
Cross-posting the original concern reported by @sander2:
- user stakes 1 KINT for 1 year. He gets 1 vKint. Stake is set to 1 vKINT.
- Wait half a year. Let's say vKINT decayed to 0.5 vKINT. Stake is still 1 vKINT
- user stakes an additional 0.00001 KINT. vKINT balance is now 0.500001 vKINT, and stake is also set to 0.500001.
- user is now earning less than if he had not staked additional funds

**Comment by gregdhill** [comment]
The proposed solution would introduce a new sort of "game" where users would compete to update each others stakes. That's probably fine but we should consider if the problem has enough impact to warrant that addition.

**Comment by sander2** [comment]
> That's probably fine but we should consider if the problem has enough impact to warrant that addition.

Imo it does. People rightfully expect their rewards to increase if they stake additional tokens or if they extend the staking period. The fact that it right now it's likely to do the opposite is imo very bad

**Comment by nakul1010** [comment]
Following is my proposal to solve the issue 

### **Extrinsic Required in Escrow Pallet**

1) `update_users_stake`

The extrinsic will be used by the bot/user to update a user's stake.

- **Parameters:**
  - origin: The user's address.
  - account: The account for which recalculation needs to be performed.

### **Team Bot**

A bot designed as a Rust binary that can perform calculations for every registered account and call the extrinsic if it finds any misconfiguration in the stake.

### **Flow Diagram**
![Update Users escrow stake](https://github.com/interlay/interbtc/assets/58786560/145e5e44-8615-4ca9-b58f-eb6baa2de51a)

**Comment by sander2** [comment]
For the first step, let's not worry about the bot. Let's first open a PR with the new extrinsic. I think the `deposit_for` function takes the _increase_ in amounts, so I think we should just be able to call `deposit_for(0,0)`.

**Comment by nakul1010** [comment]
> For the first step, let's not worry about the bot. Let's first open a PR with the new extrinsic. I think the `deposit_for` function takes the _increase_ in amounts, so I think we should just be able to call `deposit_for(0,0)`. Other than that the flow lgtm

Updated flow diagram based on the comment.
