### ISSUE TITLE
Automatically benchmark runtimes

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#1009]
We need some tooling to automatically run our benchmarks and output the weights (see the [kusama runtime structure](https://github.com/paritytech/polkadot/tree/master/runtime/kusama/src/weights) for example). I'm not sure what the best approach is but I like [Acala's setup](https://github.com/AcalaNetwork/Acala/blob/master/.github/workflows/benchmark.yml) so we can run the `/bench` command from the PR for an individual pallet or the entire runtime - although I'm not sure how these files are then committed. I took a brief look at Parity's setup and they seem to run the benchmarks elsewhere (I think GitLab) and commit the updated weights manually. Whatever solution we adopt I would like to have these run more frequently so we can catch breaking changes early - automatically running in PRs would be great but not sure if this would take too long.

**Comment by gregdhill** [comment]
```shell
cargo run --bin interbtc-parachain --features runtime-benchmarks --release -- benchmark pallet --pallet '*' --extrinsic '*' --chain kintsugi-dev --execution=wasm --wasm-execution=compiled --steps 50 --repeat 20 --output parachain/runtime/kintsugi/src/weights/ --template .deploy/weight-template.hbs
```

**Comment by sander2** [comment]
> ```shell
> cargo run --bin interbtc-parachain --features runtime-benchmarks --release -- benchmark pallet --pallet '*' --extrinsic '*' --chain kintsugi-dev --execution=wasm --wasm-execution=compiled --steps 50 --repeat 
> ```

You need to use the new runtime-specific template, so e.g.
```
cargo run --bin interbtc-parachain --features runtime-benchmarks --release -- benchmark pallet --pallet '*' --extrinsic '*' --chain kintsugi-dev --execution=wasm --wasm-execution=compiled --steps 100 --repeat 10 --output parachain/runtime/kintsugi/src/weights/ --template .deploy/runtime-weight-template.hbs
```

**Comment by sander2** [comment]
I also found these scripts used in polkadot which may be useful https://github.com/paritytech/polkadot/blob/master/scripts/ci/run_benches_for_runtime.sh https://github.com/paritytech/substrate/blob/master/scripts/run_all_benchmarks.sh
