### ISSUE TITLE
Bring your own fee tokens

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc#1026]
**Is your feature request related to a problem? Please describe.**
Allow users to pay transaction fees and security deposits (on issue) with tokens other than KINT or INTR.

**Describe the solution you'd like**
Valid fee tokens should be `ForeignAssets` or `Tokens`. Under the hood users would still use KINT/INTR but they would be swapping the other tokens for KINT/INTR.

**Describe alternatives you've considered**
Worthwhile checking how HydraDX and Acala implemented the bring-your-own fees on their parachains.

**Comment by gregdhill** [comment]
Closed by https://github.com/interlay/interbtc/pull/1054 and https://github.com/interlay/interbtc/pull/1061
