### ISSUE TITLE
Internal compiler error - unstable fingerprints

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#103]
**Describe the bug**
There's an issue with incremental compilation that prevents building tests multiple times on latest nightly.

**To Reproduce**
Run integration tests, make a change in the code and rerun.

**Additional context**
Tracking issue: https://github.com/rust-lang/rust/issues/83291

**Comment by nud3l** [comment]
@gregdhill is that issue still a problem? Haven't noticed that on any of the latest builds.
