### ISSUE TITLE
Prevent activating an already activated loans market

### ISSUE THREAD

**Issue by daniel-savu** [interlay/interbtc#1066]
The [activate_market](https://github.com/interlay/interbtc/blob/f0a0144a0cd7e512bf9b2c55e57b12e4b3b5e9c4/crates/loans/src/lib.rs#L685) extrinsic should fail if the market is already active, so as not to re-emit the `ActivatedMarket` event.

**Comment by nakul1010** [comment]
## Solutions

**Solution 1: Pass `is_active` flag to `mutate_market`**

Pros:
- Ensures the activation status is explicitly passed as a flag to the `mutate_market` function.

Cons:
- Every `mutate_market` query will now need to pass a flag, potentially increasing complexity and maintenance overhead.

**Solution 2: Add an `is_active` flag when updating `mutate_market`**

Pros:
- Allows updating the `mutate_market` function to include an `is_active` flag.
- Only emits an event if the flag is not set, reducing unnecessary event emissions.

Cons:
- If additional conditions need to be checked in the future, adding more flags can cause issues and make the code more complex.

**Solution 3: Add the `check_market_state_before_activating` function**

Pros:
- Introduces a separate function, `check_market_state_before_activating`, to ensure all necessary checks are performed before updating the market.
- Provides flexibility to modify the helper function in the future if more ensures are needed.

By implementing Solution 3, the code can benefit from a dedicated function that handles the market state checks, ensuring proper validation before activating the market. This approach offers flexibility for future modifications and enhances code readability.
