### ISSUE TITLE
Add support for `rust-bitcoin` in ink! smart contracts

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc#1144]
**Is your feature request related to a problem? Please describe.**
Building programs that interact with Bitcoin mostly use [rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin).

- ordinals: https://github.com/ordinals/ord/blob/master/Cargo.toml#L23
- lighting: https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/Cargo.toml#L43
- nostr: https://github.com/rust-nostr/nostr/blob/master/crates/nostr/Cargo.toml#L34
- bdk: https://github.com/bitcoindevkit/bdk/blob/master/crates/bdk/Cargo.toml#L19

To make the lives easy for builders, being compatible with `rust-bitcoin` allows reusing existing code in smart contracts over having to rewrite it.

**Describe the solution you'd like**

Add support for `rust-bitcoin` in ink contracts that can be deployed on Interlay.

Extend the example in https://github.com/interlay/interbtc/blob/master/contracts/btc_swap/lib.rs to use `rust-bitcoin` types instead of the parachain runtime types.

**Additional context**

`rust-bitcoin` types that are used as arguments for transactions need to implement the SCALE encoding and decoding traits. Types that are put in storage need to implement the `StorageLayout` trait.

**Comment by gregdhill** [comment]
There are two solutions to add `rust-bitcoin` support *without* forking:
- Add wrapper types (e.g. `TransactionWrapper(rust_bitcoin::Transaction)`) and manually implement `Encode` / `Decode`
- Use our custom types and provide conversions (`TryFrom` / `TryInto`) for all API boundaries (i.e. calls / storage) where SCALE codecs are required

In either case we need to pin a specific version of `rust-bitcoin`, this should also be feature-gated so it is only compiled when necessary.

**Comment by gregdhill** [comment]
On a related note we recently discussed using `rust-bitcoin` types instead of our custom definitions in the `bitcoin` crate. It was agreed there is no particular advantage for the runtime itself since even if we were able to subvert the orphan rule we now have metered "formatting" logic which would be difficult to rewrite.

**Comment by sander2** [comment]
There is a very easy way to implement the wrapper approach. The bitcoin types implement `Decodable` and `Encodable`, to decode/encode to the bitcoin serialized format. We could do something like this:

```rust
struct ScaleCodec<T: rust_bitcoin::Decodable + rust_bitcoin::Encodable>(T);

impl<T: rust_bitcoin::Decodable + rust_bitcoin::Encodable> scale::Encode for ScaleCodec<T> {
    fn encode(value: T) -> ScaleFormatted {
        let bitcoin_encoded: Vec<u8> = value.consensus_encode(); // encode into bitcoin serialized format
        return bitcoin_encoded.encode() // encode the vec using scale
    }
}
impl<T: rust_bitcoin::Decodable + rust_bitcoin::Encodable> scale::Decode for ScaleCodec<T> {
    fn decode(buf: ScaleFormatted) -> T {
        let bitcoin_encoded: Vec<u8> = buf.decode(); // decode using scale
        return bitcoin_encoded.consensus_decode() // decode from bitcoin serialized format
    }
}
impl <T: rust_bitcoin::Decodable + rust_bitcoin::Encodable>  ScaleCodec<T> {
    fn inner(self) -> T {
        self.0
    }
}
```

There are two problems with this, though.. First, weights. Second, we'll still need a conversion rust-bitcoin -> interlay-bitcoin inside the runtime.. So we'd still need the `TryFrom / TryInto` as well..

**Comment by gregdhill** [comment]
I very much like that solution for the wrapper! So I was thinking that with the wrapper we would solely use `rust-bitcoin` types but I guess for runtime interactions we would still need to convert to our types.
