### ISSUE TITLE
btc-parachain beta.json

### ISSUE THREAD

**Issue by alexchenfeng** [interlay/interbtc#163]
**Describe the bug**

When I use https://raw.githubusercontent.com/interlay/polkabtc-docs/master/scripts/beta.json start local btc-parachain , the log report  Bootnode with peer id ` 12D3KooWQgh9z6TuD7H5ixMPsa2RR6FoKp35SToCD1c2DNJqyEjU` is on a different chain (our origin: 0x7ef7.... .9fef their: 0xadc6... .866d. and the target is #1211281, **which  genesis chain beta.json** should I use?

**To Reproduce**

I'm using guide website: https://docs.polkabtc.io/#/collator/guide

**Comment by nud3l** [comment]
Thanks for the question! Probably we need to update the chain spec in the docs. @gregdhill do you think we can link the chain spec to this repo so we don't have two sources of truth?

**Comment by gregdhill** [comment]
The genesis is the docs should be the only source of truth for beta, this may be out-of-sync but we will re-genesis in the coming days.

**Comment by gregdhill** [comment]
Should be solved with https://github.com/interlay/interbtc-docs/pull/101
