### ISSUE TITLE
Rename exchange-rate-oracle to just oracle

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#220]
This pallet also stores BTC inclusion fees, so it would make sense to simplify the naming.

**Comment by nud3l** [comment]
I agree with this - should also be updated in the spec then.

**Comment by gregdhill** [comment]
Updated in the spec, will wait for multi-collateral to be merged before changing the implementation.

**Comment by gregdhill** [comment]
Resolved by https://github.com/interlay/interbtc/pull/228
