### ISSUE TITLE
Oracle offline detection with multi collateral

### ISSUE THREAD

**Issue by sander2** [interlay/interbtc#222]
**Context**
Before multicollateral, we had a simple oracle off-line detection system. If the oracle was inactive for too long, then we would stop incrementing `active_block_count`. Each bitcoin block header stored the `active_block_count` when it got relayed. An issue/redeem/replace is only cancellable when `active_block_count` increased by a certain number.

**Problem**
Now that we have multi collateral, we need to account for the possibility that one _currency_ does not get updated, and thus the exchange rate becomes invalid _for that specific currency_. Operations with other currencies should be able to continue to function.

**Solutions**
- Make oracles submit all currencies simultaneously. That way, either all currencies will be outdated, or none will be. Most of the logic can remain unchanged. The problem would be adding or removing currencies - different oracle providers will have to change the calls they are making simultaneously.
- We can halt for _all_ currencies if _one_ of them is outdated.
- We can maintain a `active_block_count` per currency. This requires additional iteration in `System`, to increment the value each block for all currencies. Note that we iterate over the currencies in the oracle anyway, so the big O complexity does not change. The client cancellation logic gets slightly complicated, but this should be manageable. We currently store `active_block_count` in bitcoin block headers, so this struct would grow some, but we might be able to store just the normal parachain height - I think we only use it to require a certain number of parachain confirmations before we accept bitcoin blocks.

I think I'm leaning to the last solution. The main downside is that it is the most complex solution, and thus has highest risk of bugs. But I feel it's the most correct solution.

**Comment by nud3l** [comment]
What is the difference between solution 1 and 2? In 1, you'd just fail the setter if not all currencies are in included and in 2 you'd allow partial setting but you'd halt if one of them is outdated. Is that correct?

My main concern is around the time when we add a new collateral currency. I think once live, the oracles would not do partial updates, but I am concerned that if we add a new collateral currency and oracles are not catching up in time that we halt the entire functionality of the chain.

On the other hand, solution 3 adds a lot of complexity on the code side that would increase with every new asset we are adding (increasing the diff for a runtime upgrade).

I am currently leaning towards solution 2 whereby we need to ensure out-of-band that our oracles are up-to-date as it is a lot simpler than solution 3 and seem to be less impactful on future runtime upgrades/slightly better for performance as well.

But I would also like to hear what @alexeiZamyatin and @gregdhill are thinking.

**Comment by sander2** [comment]
> What is the difference between solution 1 and 2? In 1, you'd just fail the setter if not all currencies are in included and in 2 you'd allow partial setting but you'd halt if one of them is outdated. Is that correct?

Yea in solution 1 it'd be mandatory for all oracles to supply all exchange rates at the same time, otherwise `feed_values` returns an error. This way you don't need separate offline detection per currency - either all are outdated or none are. In the second solution, you allow the omission of currencies in `feed_values`, so you have to do offline detection per currency. When a single currency is considered offline, this solution marks _all_ of them as offline (such that most of the system can remain unchanged). 

> My main concern is around the time when we add a new collateral currency.

We could implement some activation logic. I.e. right after adding a new currency, oracles can start including the new exchange rates in their submissions, but the currency does not become active until a certain number of vaults include the new exchange rate. Until the activation, vaults can not register with the currency, and an insufficient number of inclusions does not trigger an oracle offline event.

The number of required active oracle feeds for 'activation' could be higher than the minimum number required to be considered offline. E.g. activate only when it is included by 3 oracles, but don't trigger 'oracle offline' unless the number of oracles is _strictly less than_ 2.

**Comment by gregdhill** [comment]
Guess it could prove tricky to enforce that all oracles have all price feeds, but I would certainly prefer that to the additional complexity introduced in the other strategy.

On a related note, there are many reasons why an oracle may no longer provide a particular price feed - e.g. attack on the origin network. How do we plan to deprecate a currency? This might be worth splitting into a separate research ticket.

**Comment by nud3l** [comment]
I think we'll have to operate under the assumptions that:
1. We will allow only a few currencies as collateral where we can reliable get price data for
2. Not all oracles might provide price data for all assets, e.g., I can imagine that if we add staking derivatives, only Polkadot specific oracles might provide prices for that whereas other oracles might lag behind

My current preference is option 2 since it's the most simple to implement and under the assumption that we have at least one oracle submitting prices for each asset, this works.

> On a related note, there are many reasons why an oracle may no longer provide a particular price feed - e.g. attack on the origin network. How do we plan to deprecate a currency? This might be worth splitting into a separate research ticket.
You mean an attack on the oracle network or an attack on the currency we want to get the prices for?
