### ISSUE TITLE
Oracle optimisations

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#223]
- Cleanup `RawValues` when outdated
- Use checked-math in `begin_block`
- More general error for `MissingExchangeRate` - can be tx fees

**Comment by nud3l** [comment]
Should this rather be ticketed in notion?

**Comment by gregdhill** [comment]
It's good to use GitHub issues for things that could benefit from community review.

**Comment by nud3l** [comment]
> It's good to use GitHub issues for things that could benefit from community review.

In that case, the issue needs more context and information. It should be standard to use the GitHub issue templates and follow the questions there. Even to me it is quite unclear what the purpose of this issue is. Seems like a todo list of things that could be changed, but I'm not entirely sure.

**Comment by gregdhill** [comment]
For now this was more of a TODO list for me I made when reviewing the oracle code. I'll close for now since there is nothing imminently actionable.
