### ISSUE TITLE
Relaychain DB errors

### ISSUE THREAD

**Issue by Curu24** [interlay/interbtc#368]
**Describe the bug**
Running the same setup on 3 machines.
VPS 1. No problem, synced using RocksDb from polkashots.io (after 0.9.12 update)
VPS 2. Problem with RocksDb - giving error: Unsupported BABE DB version: 3. Then I tried letting it sync by itself and succeeded.
VPS 3. Problem with RocksDb - giving error: Unsupported BABE DB version: 3. 
- Then I tried letting it sync by itself after finishing it gave error: [Relaychain] DB has been previously marked as corrupted, attempting repair, Error: Service(Client(Backend("Corruption: force_consistency_checks: L0 files seqno 865146853 865787239 1808995 vs. 865524326 865626223 1810803")))
- Another syncing attempt resulted in this error:
DatabaseError(DatabaseError(Custom { kind: Other, error: Error { message: "IO error: No such file or directory: While open a file for appending: /home/kintsugi_user/kintsugi/polkadot/chains/ksmcc3/db/full/008326.log: No such file or directory" } }))
- After trying private relaychain snapshot from Dominik, got this error: Error: Service(Client(Backend("Invalid argument: Column families not opened: col11, col10, col9, col8, col7, col6, col5, col4, col3, col2, col1, col0")))

**To Reproduce**
Running as a systemd service:

[Unit]
Description=Kintsugi full node

[Service]
User=kintsugi_user
Group=kintsugi_user
ExecStart=/usr/local/bin/interbtc-parachain \
  --name=Polkadotters \
  --base-path=/home/kintsugi_user/kintsugi \
  --telemetry-url "wss://telemetry.interlay.io/submit 0" \
  --chain=kintsugi \
  --execution=wasm \
  --wasm-execution=compiled \
  --unsafe-ws-external \
  --rpc-methods=unsafe \
  --pruning=archive \
  -- \
  --rpc-cors=all \
  --no-telemetry \
  --execution=wasm \
  --wasm-execution=compiled \
  --database=RocksDb \
  --unsafe-pruning \
  --pruning=1000

Restart=always
RestartSec=120

[Install]
WantedBy=multi-user.target

**Expected behavior**
Errors from the bug description

**Version / Commit (e.g. 1.0.0):**
version 1.2.0-0f43318-x86_64-linux-gnu

**Additional context**
-

**Comment by gregdhill** [comment]
Closing, @Curu24 please re-open if necessary.
