### ISSUE TITLE
Node synchronization is faulty

### ISSUE THREAD

**Issue by COLUD4** [interlay/interbtc#463]
![截屏2021-12-28 下午5 04 40](https://user-images.githubusercontent.com/21240219/147549131-b0c47b50-3069-47e5-9b9f-bd85812a6f4a.png)
1、The block corresponding to Best has not been updated for a long time and will be restored after the node is restarted.
2、[finalized #59647] Synchronous slow

**Comment by nud3l** [comment]
Closing since that issue should be resolved by now.
