### ISSUE TITLE
Error calling Oracle RPCs

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#621]
Take this call as an example:

```rust
fn collateral_to_wrapped(
    amount: BalanceWrapper<Balance>,
    currency_id: CurrencyId,
) -> Result<BalanceWrapper<Balance>, DispatchError>;
```

`BalanceWrapper` has the following concrete type:

```rust
pub struct BalanceWrapper {
    pub amount: u128,
}
```

For some reason `polkadot-js/apps` requires a second `CurrencyId` in the `amount` which results in the following error:

![image](https://user-images.githubusercontent.com/12613821/170703400-266596d7-b606-43b0-abc0-7992d0310d41.png)

**Comment by jacogr** [comment]
See your definitions (currencyId + amount) - https://github.com/interlay/interbtc-types/blob/bb448280cfba1ad585eb78880a94a5c0840a195b/definitions.json#L9-L12
