### ISSUE TITLE
Tracking issue for AMM support

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#712]
Integrate [Zenlink's DEX module](https://github.com/zenlinkpro/Zenlink-DEX-Module) ([docs](https://wiki.zenlink.pro/)).

## Notes

No XCM integration for now, see: https://github.com/zenlinkpro/Zenlink-DEX-Module/issues/36#issuecomment-1237799548

### Standard AMM

- Adopts the Uniswap v2 mechanism
- Supports bootstrapping with incentives
- Optional protocol fee

**Root extrinsics:**
- set fee receiver
- set fee point (maximum 0.3%)
- create pair
- bootstrap create

### Stable AMM

- Based on Curve v1 (StableSwap) model
- Focuses on similarly priced assets
- Minimizes impermanent loss and slippage
- Supports multiple assets per pool

**Root extrinsics:**
- create base / meta pool
- set fee receiver
- set swap fee
- set admin fee
- start / stop ramp (amplification co-efficient)

## Resources
- https://github.com/zenlinkpro/dex-sdk
- https://github.com/zenlinkpro/zenlink-security-audit
- https://github.com/zenlinkpro/token-list

**Comment by nud3l** [comment]
@gregdhill can this be closed?
