### ISSUE TITLE
Remove nomination pallet

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#721]
We have unfortunately never used the nomination logic on mainnet and it seems we never will. The goal now is to reduce complexity by removing the pallet and associated code:

- [ ] Remove nomination pallet
- [ ] Remove integration tests
- [ ] Remove staking pallet

If we do remove the staking pallet, and instead use just the reward pallet, we will need to migrate the stake back into the Vault struct.

**Comment by sander2** [comment]
We'll modify the pallet for trusted nomination
