### ISSUE TITLE
Probable bug on slot assignment for round robin

### ISSUE THREAD

**Issue by Poggi-Luca** [interlay/interbtc#750]
Hello Kintsugi Team, I'm Luca from :ice_cube: Iceberg Nodes :ice_cube: 

It seems that slot assignment is skipping a slot on block assignment (also confirmed by node logs: no candidate block produced).
Look at the following pictures:
![image](https://user-images.githubusercontent.com/59626126/199958987-f5837113-5d39-4ab8-92b8-3cfaae1b83cf.png)
![image](https://user-images.githubusercontent.com/59626126/199959041-62ad1f91-8cac-4872-9507-0e1f5291947f.png)

Every two relaychain blocks (6 sec), we have only one parachain block (12 sec), and this led to skip a slot for block assignment.

As you can see in the following picture, we produced a block just because someone else missed his block (but this is completely random):
![image](https://user-images.githubusercontent.com/59626126/199959387-b72b094b-8031-495b-946d-ecb95ab80fb7.png)

It seems a bug similar to previously discovered bug on Calamari: https://github.com/Manta-Network/Manta/issues/845

Please let me know if you need additional informations
Waiting for your kind reply

**Comment by gregdhill** [comment]
I think this was resolved by #883, please re-open if that is not the case.
