### ISSUE TITLE
Make governance proposal/referendum schedule timestamp dependent instead of block number dependent

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc#784]
**Is your feature request related to a problem? Please describe.**
Due to block time variance, proposals and referenda can execute any day of the week. The intended duration for proposals and referenda is encoded in days. However, these estimates are inaccurate as block times vary.

**Describe the solution you'd like**
Change the block time-based proposals/referenda schedule to a timestamp-based solution that maintains the correct cadence. No governance upgrades on the weekend.

**Describe alternatives you've considered**
Fixing block times is outside of our control due to this being a restriction on the Kusama/Polkadot relay chains. Plus, the issue might get worse depending on decentralized collator performance. I don't have a good alternative to my approach above.

**Comment by gregdhill** [comment]
Timestamp manipulation is the primary concern, depending on how much skew Polkadot's consensus allows in this case it may be possible for a collator to delay the enactment of a proposal. I'm not sure that's of huge concern and we may wish to tolerate that for the sake of simplicity.

**Comment by nud3l** [comment]
Polkadot has a check on the timestamps:

https://wiki.polkadot.network/docs/learn-transaction-fees#advanced
> Rather, validators accept or reject the block based on how reasonable they find the timestamp. In Polkadot, it must be within some acceptable range of their own system clocks.

Not sure exactly how big the difference is, but I don't see an apparent attack vector by switching to timestamps instead of block numbers. With block numbers, a collator might also withhold a block for longer to delay delivery or might produce the block faster.

**Comment by nud3l** [comment]
Closing this issue in favor of #803
