### ISSUE TITLE
Vault Capacity Rewards do not take into consideration accept_new_issues(false)

### ISSUE THREAD

**Issue by sander2** [interlay/interbtc#881]
As title says. Vaults can disable issuing and still get rewards as if their whole collateral is available. What should probably happen is that vault's stake in the reward pool gets set to the collateral that is actually used to back issued tokens, divided by the secure threshold. Or equivalently, to `vault.issuedTokens.convert_to(vault.collateral_currency())`. The problem is that this amount changes whenever the exchange rate changes, and we can't go and iterate over the vaults to update their reward stakes whenever that happens.. Maybe we should just set their reward stake to 0?

**Comment by nud3l** [comment]
Yep, that is a bug. Reward stake should be 0 when issuing is disabled. Setting stake to 0 looks like a good solution.
