### ISSUE TITLE
Document different currencies for integrations

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc#894]
**Is your feature request related to a problem? Please describe.**
The asset docs are currently outdated as they are missing the `LendToken`, `LpToken` and `StableLpToken`.

**Describe the solution you'd like**

Add a description to https://docs.interlay.io/#/developers/api?id=asset-api how wallets and other partners would query the assets. This would include a way how they can figure out which `LendToken`, `LpToken` and `StableLpToken` belong to which market or pool.

On possibility is to add a table similar to `ForeignAssets`.

**Describe alternatives you've considered**

It would be nice to get this info from the chain directly but that would be a bit more involved I feel.

**Comment by gregdhill** [comment]
Closed by https://github.com/interlay/interlay.github.io/pull/301 and https://github.com/interlay/interlay.github.io/pull/300
