### ISSUE TITLE
Add vault_id to the IncreaseLockedcollateral and DecreaseLockedCollateral 

### ISSUE THREAD

**Issue by jtfirek** [interlay/interbtc#898]
**Is your feature request related to a problem? Please describe.**
Dom would like me to add more information to the vault scalar over on the squid side of things. I need to update the locked collateral amount on events like VaultRegistryDecreaseLockedCollateralEvent and VaultRegistryIncreaseLockedCollateralEvent. The only issue these events don't contain the vault_id value that I need.
https://github.com/interlay/interbtc/blob/1a1afa90228f37c9ade4acbda8275c2f5cfe85ce/crates/vault-registry/src/lib.rs#L421-L430
**Describe the solution you'd like**
I would like to add vault_id to these events I am referring too.

**Additional context**
I might be on the wrong track here as I am new to the codebases!

**Comment by gregdhill** [comment]
These events are used to track the total amount of collateral locked, you should use `DepositCollateral` and `WithdrawCollateral` (from the Nomination pallet) to track the individual amounts locked per Vault.
