### ISSUE TITLE
Require preimage submission before proposals can be made

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc#951]
**Is your feature request related to a problem? Please describe.**
Users can make governance proposals without submitting the preimage first. Proposals/referenda can be voted on without actually knowing what the proposal is encoding.

**Describe the solution you'd like**
Require that the preimage is submitted (via `note_preimage`) before the user makes a new proposal (via `propose`).

**Additional context**
See thread about malicious governance proposals: https://twitter.com/adamsteeber1/status/1628196215572639744?s=61&t=UctmNuHtkXXYCaiTaEXNgQ

**Comment by gregdhill** [comment]
Closed by https://github.com/interlay/interbtc/pull/949/commits/5868ba7862278246d4872c390910ecdea7542282
