### ISSUE TITLE
Remove testnet runtimes?

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#956]
We added the `sudo` pallet back into the `interlay` and `kintsugi` runtimes (with the key disabled) to simplify testing with chopsticks (see [here](https://github.com/interlay/interbtc/pull/816)) which was the only major difference with the testnet runtimes - apart from the recent additions of Lending and AMM which we could feature-gate if necessary. We should consider deprecated the separate testnet runtimes to reduce the amount of code we have to maintain. Also worth noting the "standalone" node will be removed when [this PR](https://github.com/interlay/interbtc/pull/772) is merged.

**Comment by nud3l** [comment]
Didn't we remove sudo again from the mainnet runtimes?

**Comment by gregdhill** [comment]
No we included it again [here](https://github.com/interlay/interbtc/pull/816) but we removed the explicit key for mainnet [here](https://github.com/interlay/interbtc/pull/938).

**Comment by nud3l** [comment]
Gotcha, thanks!

On the issue itself, I think it would make sense to remove the testnet runtimes and feature gate instead.
