### ISSUE TITLE
Reconsider griefing collateral recipient

### ISSUE THREAD

**Issue by sander2** [interlay/interbtc#994]
Now that we have the vault capacity model change, vaults are no longer negatively impacted by receiving issues that do not get executed. As such, we may want to consider slashing the griefing collateral of failed issues to either the vault reward pool, or to treasury

**Comment by gregdhill** [comment]
@sander2 we actually specifically changed this because of the vault capacity model change, see this PR: https://github.com/interlay/interbtc/pull/820

**Comment by sander2** [comment]
> @sander2 we actually specifically changed this because of the vault capacity model change, see this PR: #820

My bad, closing
